# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Python APP

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./src/requirements.txt ]; then pip install -r ./src/requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESSTOKEN}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          iagopattas/glasses-dashboard-backend:${{github.sha}}
          iagopattas/glasses-dashboard-backend:latest
